apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myimage-deployment
      track: stable
  template:
    metadata:
      labels:
        app: myimage-deployment
    spec:
      containers:
      - name: mycontainer
        image: myimage
        ports:
        - containerPort: 80
